image_info_dict = {
    'rws_tarot_00_fool.jpg': {'name': '愚者-0(the fool)', 'upright': '開端、自由、純真、獨創性、冒險、理想主義、自發性', 'reversed': '魯莽、粗心、分心、幼稚、愚蠢、容易上當、陳舊、遲鈍'},
    'rws_tarot_01_magician.jpg': {'name': '魔術師-1(the magician)', 'upright': '意志力、慾望、足智多謀、技能、能力、專注、表現', 'reversed': '操縱、狡猾、詭計、浪費天賦、錯覺、欺騙'},
    'rws_tarot_02_high_priestess.jpg': {'name': '女祭司-2(the high priestess)', 'upright': '無意識、直覺、神秘、靈性、更高的力量、內在的聲音', 'reversed': '被壓抑的直覺、隱藏的動機、膚淺、困惑、認知失調'},
    'rws_tarot_03_empress.jpg': {'name': '女皇-3(the mepress)', 'upright': '神聖的女性、性感、生育力、培育、創造力、美麗、豐富、自然', 'reversed': '不安全、專橫、疏忽、窒息、缺乏成長、缺乏進步'},
    'rws_tarot_04_emperor.jpg': {'name': '皇帝-4(the emperor)', 'upright': '穩定性、結構、保護、權威、控制、實用性、重點、紀律', 'reversed': '暴君、霸道、死板、固執、缺乏紀律、魯莽'},
    'rws_tarot_05_hierophant.jpg': {'name': '教宗-5(the hierophant)', 'upright': '傳統、社會群體、約定俗成、從眾、教育、知識、信仰', 'reversed': '叛逆、非常規、不循規蹈矩、新方法、無知'},
    'rws_tarot_06_lovers.jpg': {'name': '戀人-6(the lovers)', 'upright': '愛、工會、夥伴關係、關係、選擇、浪漫、平衡、團結', 'reversed': '不和諧、不平衡、衝突、超脫、錯誤的選擇、優柔寡斷'},
    'rws_tarot_07_chariot.jpg': {'name': '戰車-7(the chariot)', 'upright': '成功、雄心、決心、意志力、控制力、自律、專注', 'reversed': '有力、沒有方向、沒有控制、無力、侵略、障礙'},
    'rws_tarot_08_strength.jpg': {'name': '力量-8(strength)', 'upright': '勇氣、勇敢、自信、同情、自信、內在力量', 'reversed': '自我懷疑、軟弱、低信心、不足、怯懦、強硬'},
    'rws_tarot_09_hermit.jpg': {'name': '隱士-9(the hermit)', 'upright': '自我反省、內省、沉思、退縮、孤獨、尋找自我', 'reversed': '孤獨、孤立、隱居、反社會、拒絕、回歸社會'},
    'rws_tarot_10_wheel_of_fortune.jpg': {'name': '命運之輪-10(wheel of fortune)', 'upright': '變化、週期、命運、決定性時刻、運氣、財富、突發事件', 'reversed': '運氣不好、缺乏控制、執著於控制、不受歡迎的變化、延誤'},
    'rws_tarot_11_justice.jpg': {'name': '正義-11(justice)', 'upright': '正義、業力、後果、責任、法律、真相、誠實、正直、因果', 'reversed': '不公正、報復、不誠實、腐敗、不誠實、不公平、逃避責任'},
    'rws_tarot_12_hanged_man.jpg': {'name': '倒吊人-12(the hanged man)', 'upright': '犧牲、等待、不確定、缺乏方向、視角、沉思', 'reversed': '拖延、漠不關心、停滯不前、避免犧牲、冷漠'},
    'rws_tarot_13_death.jpg': {'name': '死神-13(death)', 'upright': '轉變、結局、改變、過渡、放手、釋放', 'reversed': '害怕改變、重複消極的模式、抵制改變、停滯不前、腐朽'},
    'rws_tarot_14_temperance.jpg': {'name': '節制-14(mperance)', 'upright': '平衡、和平、耐心、適度、平靜、安寧、和諧、寧靜', 'reversed': '不平衡、過度、極端、不和諧、魯莽、倉促'},
    'rws_tarot_15_devil.jpg': {'name': '惡魔-15(the devil)', 'upright': '壓迫、成癮、痴迷、依賴、過度、無力、局限', 'reversed': '獨立、自由、啟示、釋放、收回權力、收回控制'},
    'rws_tarot_16_tower.jpg': {'name': '高塔-16(the tower)', 'upright': '災難、破壞、劇變、創傷、突變、混亂', 'reversed': '避免災難、延遲不可避免的、抵制變化'},
    'rws_tarot_17_star.jpg': {'name': '星星-17(the star)', 'upright': '希望、靈感、積極性、信念、更新、治愈、復興', 'reversed': '絕望、絕望、消極、缺乏信心、沮喪'},
    'rws_tarot_18_moon.jpg': {'name': '月亮-18(the moon)', 'upright': '錯覺、直覺、不確定性、困惑、複雜性、秘密、無意識', 'reversed': '恐懼、欺騙、焦慮、誤解、曲解、清晰、理解'},
    'rws_tarot_19_sun.jpg': {'name': '太陽-19(the sun)', 'upright': '幸福、成功、樂觀、活力、喜悅、自信、真理', 'reversed': '幸福受阻、過度熱情、悲觀、不切實際的期望、自負'},
    'rws_tarot_20_judgement.jpg': {'name': '審判-20(judgement)', 'upright': '自我評價、覺醒、更新、目的、反思、清算', 'reversed': '自我懷疑、缺乏自我意識、未能吸取教訓、自我厭惡'},
    'rws_tarot_21_world.jpg': {'name': '世界-21(the world)', 'upright': '完成、成就、成就感、歸屬感、整體性、和諧', 'reversed': '缺乏封閉感、缺乏成就感、感覺不完整、空虛'},
}
